remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Test page
description: I want to be able to use pages, but I feel to stupid to do so
